package com.alligator.market.domain.common.exception;

public enum DomainErrorCodes {

    /* Провайдеры: */
    PROVIDER_CODE_DUPLICATE,
    PROVIDER_DISPLAY_NAME_DUPLICATE,
    HANDLER_NOT_FOUND,
    INSTRUMENT_NOT_SUPPORTED,
    INSTRUMENT_WRONG_CLASS,
    INSTRUMENT_WRONG_TYPE,

    /* Валюты: */
    CURRENCY_ALREADY_EXISTS,
    CURRENCY_NAME_DUPLICATE,
    CURRENCY_NOT_FOUND,
    CURRENCY_USED_IN_FX_SPOT,
    CURRENCY_CREATE_FAILED,
    CURRENCY_UPDATE_FAILED,
    CURRENCY_DELETE_FAILED,

    /* FX_SPOT инструмент: */
    FX_SPOT_ALREADY_EXISTS,
    FX_SPOT_NOT_FOUND,
    FX_SPOT_SAME_CURRENCIES,
    FX_SPOT_CREATE_FAILED,
    FX_SPOT_UPDATE_FAILED,
    FX_SPOT_DELETE_FAILED
}
