CREATE TABLE provider_catalog (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    provider_code     VARCHAR(50)  NOT NULL,
    display_name      VARCHAR(50)  NOT NULL,
    delivery_mode     VARCHAR(10)  NOT NULL,
    access_method     VARCHAR(20)  NOT NULL,
    supports_bulk_subscription BOOLEAN NOT NULL,
    min_poll_period_ms INTEGER     NOT NULL,
    CONSTRAINT pk_provider_catalog PRIMARY KEY (id)
);

ALTER TABLE provider_catalog
    ADD CONSTRAINT uq_provider_code UNIQUE (provider_code);
ALTER TABLE provider_catalog
    ADD CONSTRAINT uq_display_name UNIQUE (display_name);

CREATE TABLE provider_catalog_instrument_type (
    provider_id    BIGINT       NOT NULL,
    instrument_type VARCHAR(20) NOT NULL,
    CONSTRAINT fk_provider_instrument_type_provider FOREIGN KEY (provider_id)
        REFERENCES provider_catalog (id)
);

ALTER TABLE provider_catalog_instrument_type
    ADD CONSTRAINT pk_provider_instrument_type PRIMARY KEY (provider_id, instrument_type);
