CREATE TABLE currency
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    code              VARCHAR(3)                              NOT NULL,
    name              VARCHAR(50)                             NOT NULL,
    country           VARCHAR(100)                            NOT NULL,
    decimal           INTEGER                                 NOT NULL,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

ALTER TABLE currency
    ADD CONSTRAINT uq_currency_code UNIQUE (code);

ALTER TABLE currency
    ADD CONSTRAINT uq_currency_country UNIQUE (country);

ALTER TABLE currency
    ADD CONSTRAINT uq_currency_name UNIQUE (name);