CREATE TABLE instrument (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    type VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_via VARCHAR(255) NOT NULL,
    updated_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_via VARCHAR(255) NOT NULL,
    CONSTRAINT uq_instrument_code UNIQUE (code)
);

CREATE INDEX idx_instrument_type ON instrument (type);
