CREATE TABLE ccypair
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    code1             VARCHAR(3)                              NOT NULL,
    code2             VARCHAR(3)                              NOT NULL,
    pair              VARCHAR(6)                              NOT NULL,
    decimal           INTEGER                                 NOT NULL,
    CONSTRAINT pk_ccypair PRIMARY KEY (id)
);

ALTER TABLE ccypair
    ADD CONSTRAINT uq_currency_pair UNIQUE (pair);

ALTER TABLE ccypair
    ADD CONSTRAINT fk_pair_code1 FOREIGN KEY (code1) REFERENCES currency (code);

ALTER TABLE ccypair
    ADD CONSTRAINT fk_pair_code2 FOREIGN KEY (code2) REFERENCES currency (code);
