CREATE TABLE fx_pair_streaming_cfg
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    pair_id           BIGINT                                NOT NULL,
    provider          VARCHAR(50)                           NOT NULL,
    priority          SMALLINT                              NOT NULL,
    refresh_ms        INTEGER                               NOT NULL,
    enabled           BOOLEAN                               NOT NULL,
    CONSTRAINT pk_fx_pair_streaming_cfg PRIMARY KEY (id)
);

ALTER TABLE fx_pair_streaming_cfg
    ADD CONSTRAINT fk_stream_cfg_pair FOREIGN KEY (pair_id) REFERENCES ccypair (id);

ALTER TABLE fx_pair_streaming_cfg
    ADD CONSTRAINT uq_fx_pair_streaming_cfg_pair_provider UNIQUE (pair_id, provider);
