CREATE TABLE market_data_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(50) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    delivery_mode VARCHAR(10) NOT NULL,
    access_method VARCHAR(20) NOT NULL,
    bulk_subscription BOOLEAN NOT NULL,
    min_update_interval_seconds BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_via VARCHAR(255) NOT NULL,
    updated_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_via VARCHAR(255) NOT NULL,
    CONSTRAINT uq_provider_code UNIQUE (provider_code),
    CONSTRAINT uq_provider_display_name UNIQUE (display_name),
    CONSTRAINT chk_market_data_provider CHECK (
        min_update_interval_seconds >= 1
        AND provider_code = UPPER(provider_code)
        AND provider_code ~ '^[A-Z0-9_.-]+$'
        AND delivery_mode IN ('PULL', 'PUSH')
        AND access_method IN ('API_POLL', 'WEBSOCKET', 'FIX_PROTOCOL')
    )
);
