CREATE TABLE instrument_feed_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL,
    provider_code VARCHAR(50) NOT NULL,
    feed_role VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL,
    version BIGINT NOT NULL,
    created_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_via VARCHAR(255) NOT NULL,
    updated_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_via VARCHAR(255) NOT NULL,
    CONSTRAINT fk_ifc_instrument FOREIGN KEY (instrument_id) REFERENCES instrument (id),
    CONSTRAINT uq_ifc_instrument_feed_role UNIQUE (instrument_id, feed_role),
    CONSTRAINT uq_ifc_instrument_provider_code UNIQUE (instrument_id, provider_code),
    CONSTRAINT chk_instrument_feed_config CHECK (
        provider_code = UPPER(provider_code)
        AND provider_code ~ '^[A-Z0-9_.-]+$'
        AND feed_role IN ('PRIMARY', 'SECONDARY')
    )
);

CREATE INDEX idx_ifc_enabled ON instrument_feed_config (enabled);
