CREATE TABLE provider
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    name              VARCHAR(50)  NOT NULL,
    base_url          VARCHAR(255) NOT NULL,
    mode              VARCHAR(4)   NOT NULL,
    api_key           VARCHAR(255) NOT NULL,
    CONSTRAINT pk_provider PRIMARY KEY (id)
);

ALTER TABLE provider
    ADD CONSTRAINT uq_provider_name UNIQUE (name);
