package com.alligator.market.backend.instrument.asset.forex.reference.currency.persistence.jooq.repository;

import com.alligator.market.backend.instrument.asset.forex.reference.currency.application.exception.CurrencyAlreadyExistsException;
import com.alligator.market.backend.instrument.asset.forex.reference.currency.application.exception.CurrencyNameDuplicateException;
import com.alligator.market.backend.instrument.asset.forex.reference.currency.application.exception.CurrencyNotFoundException;
import com.alligator.market.domain.instrument.asset.forex.reference.currency.Currency;
import com.alligator.market.domain.instrument.asset.forex.reference.currency.vo.CurrencyCode;
import org.jooq.DSLContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jooq.JooqTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.TestConfiguration;
import org.springframework.test.context.TestPropertySource;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/*
 * Интеграционные тесты jOOQ-адаптера репозитория валют.
 */
@Tag("dev")
@JooqTest
@Import(JooqCurrencyRepositoryAdapterTest.Config.class)
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:currency_repo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password="
})
class JooqCurrencyRepositoryAdapterTest {

    @Autowired
    private DSLContext dsl;

    @Autowired
    private JooqCurrencyRepositoryAdapter repository;

    @BeforeEach
    void setUpSchema() {
        dsl.execute("drop table if exists currency");
        dsl.execute("""
                create table currency (
                    id bigint generated by default as identity primary key,
                    code varchar(3) not null,
                    name varchar(50) not null,
                    country varchar(100) not null,
                    fraction_digits integer not null,
                    constraint uq_currency_code unique (code),
                    constraint uq_currency_name unique (name)
                )
                """);
    }

    @Test
    @DisplayName("create: успешно создает валюту")
    void createSuccess() {
        Currency created = repository.create(currency("USD", "US Dollar", "United States", 2));

        assertThat(created.code()).isEqualTo(CurrencyCode.of("USD"));
        assertThat(created.name()).isEqualTo("US Dollar");
        assertThat(created.country()).isEqualTo("United States");
        assertThat(created.fractionDigits()).isEqualTo(2);
    }

    @Test
    @DisplayName("create: duplicate code -> CurrencyAlreadyExistsException")
    void createDuplicateCode() {
        repository.create(currency("USD", "US Dollar", "United States", 2));

        assertThatThrownBy(() -> repository.create(currency("USD", "Another Name", "Canada", 2)))
                .isInstanceOf(CurrencyAlreadyExistsException.class);
    }

    @Test
    @DisplayName("create: duplicate name -> CurrencyNameDuplicateException")
    void createDuplicateName() {
        repository.create(currency("USD", "US Dollar", "United States", 2));

        assertThatThrownBy(() -> repository.create(currency("CAD", "US Dollar", "Canada", 2)))
                .isInstanceOf(CurrencyNameDuplicateException.class);
    }

    @Test
    @DisplayName("update: успешно обновляет валюту")
    void updateSuccess() {
        repository.create(currency("EUR", "Euro", "Eurozone", 2));

        Currency updated = repository.update(currency("EUR", "Euro Updated", "EU", 3));

        assertThat(updated.name()).isEqualTo("Euro Updated");
        assertThat(updated.country()).isEqualTo("EU");
        assertThat(updated.fractionDigits()).isEqualTo(3);
    }

    @Test
    @DisplayName("update: отсутствующая валюта -> CurrencyNotFoundException")
    void updateMissingCurrency() {
        assertThatThrownBy(() -> repository.update(currency("CHF", "Swiss Franc", "Switzerland", 2)))
                .isInstanceOf(CurrencyNotFoundException.class);
    }

    @Test
    @DisplayName("update: duplicate name -> CurrencyNameDuplicateException")
    void updateDuplicateName() {
        repository.create(currency("USD", "US Dollar", "United States", 2));
        repository.create(currency("CAD", "Canadian Dollar", "Canada", 2));

        assertThatThrownBy(() -> repository.update(currency("CAD", "US Dollar", "Canada", 2)))
                .isInstanceOf(CurrencyNameDuplicateException.class);
    }

    @Test
    @DisplayName("deleteByCode: успешно удаляет валюту")
    void deleteSuccess() {
        repository.create(currency("JPY", "Yen", "Japan", 0));

        repository.deleteByCode(CurrencyCode.of("JPY"));

        assertThat(repository.findByCode(CurrencyCode.of("JPY"))).isEmpty();
    }

    @Test
    @DisplayName("deleteByCode: отсутствующая валюта -> CurrencyNotFoundException")
    void deleteMissingCurrency() {
        assertThatThrownBy(() -> repository.deleteByCode(CurrencyCode.of("JPY")))
                .isInstanceOf(CurrencyNotFoundException.class);
    }

    @Test
    @DisplayName("findByCode: возвращает empty для отсутствующей валюты")
    void findByCodeAbsent() {
        Optional<Currency> found = repository.findByCode(CurrencyCode.of("GBP"));

        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("findAll: возвращает валюты отсортированные по code asc")
    void findAllSortedByCode() {
        repository.create(currency("USD", "US Dollar", "United States", 2));
        repository.create(currency("AUD", "Australian Dollar", "Australia", 2));
        repository.create(currency("EUR", "Euro", "Eurozone", 2));

        List<Currency> all = repository.findAll();

        assertThat(all)
                .extracting(c -> c.code().value())
                .containsExactly("AUD", "EUR", "USD");
    }

    /*
     * Вспомогательный factory для компактного создания доменной модели валюты в тестах.
     */
    private static Currency currency(String code, String name, String country, int fractionDigits) {
        return new Currency(CurrencyCode.of(code), name, country, fractionDigits);
    }

    @TestConfiguration(proxyBeanMethods = false)
    static class Config {

        @Bean
        JooqCurrencyRepositoryAdapter jooqCurrencyRepositoryAdapter(DSLContext dsl) {
            return new JooqCurrencyRepositoryAdapter(dsl);
        }
    }
}
