DROP TRIGGER IF EXISTS trg_refresh_source_plan_execution_status_after_source_plan_inse ON source_plan;
DROP TRIGGER IF EXISTS trg_refresh_source_plan_execution_status_after_source_plan_insert ON source_plan;
DROP TRIGGER IF EXISTS trg_source_plan_exec_status_after_plan_insert ON source_plan;

DROP TRIGGER IF EXISTS trg_refresh_source_plan_execution_status_after_entry_change ON source_plan_entry;
DROP TRIGGER IF EXISTS trg_source_plan_exec_status_after_entry_change ON source_plan_entry;

DROP TRIGGER IF EXISTS trg_refresh_source_plan_execution_status_after_capturer_change ON market_data_capturer_passport;
DROP TRIGGER IF EXISTS trg_source_plan_exec_status_after_capturer_change ON market_data_capturer_passport;

DROP TRIGGER IF EXISTS trg_refresh_source_plan_execution_status_after_source_change ON market_data_source_passport;
DROP TRIGGER IF EXISTS trg_source_plan_exec_status_after_source_change ON market_data_source_passport;

DROP FUNCTION IF EXISTS refresh_source_plan_execution_status();
