# ===============================
# APPLICATION
# ===============================
spring.application.name=backend

# ===============================
# TIME CONFIGURATION
# ===============================
app.time.business-zone-id=Europe/Moscow

# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.datasource.username=postgres
spring.datasource.password=1234

# ===============================
# FLYWAY MIGRATION
# ===============================
spring.flyway.enabled=false

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=never

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.root=INFO
logging.level.com.alligator.market=INFO
logging.level.reactor.netty.http.client=INFO
logging.file.path=logs

# ==================================
# MARKET DATA PROVIDER CONFIGURATION
# ==================================
# MOEX ISS connection configuration:
provider.connection-properties.moex.iss.fx-spot.base-url=https://iss.moex.com/iss
