# ===============================
# APPLICATION
# ===============================
spring.application.name=backend
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.datasource.username=postgres
spring.datasource.password=1234
# ===============================
# FLYWAY MIGRATION
# ===============================
spring.flyway.enabled=false
spring.flyway.validate-on-migrate=true
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.root=INFO
logging.level.com.alligator.market=INFO
logging.level.reactor.netty.http.client=INFO
logging.file.path=logs
# ===============================
# KAFKA CONFIGURATION
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.schema.registry.url=http://localhost:8082
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
# ==================================
# MARKET DATA PROVIDER CONFIGURATION
# ==================================
provider.sync.on-startup=true
provider.sync.fail-fast=false
# TwelveData connection configuration:
provider.connection-config.twelve-free.base-url=https://api.twelvedata.com
provider.connection-config.twelve-free.api-key=2b8e2659372340d5b922cd6b8d6d2cb2
# ProFinanceParse connection configuration:
provider.connection-config.profinance.base-url=https://www.profinance.ru
