# ===============================
# APPLICATION
# ===============================
spring.application.name=backend
# ===============================
# TIME CONFIGURATION
# ===============================
app.time.business-zone-id=Europe/Moscow
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.datasource.username=postgres
spring.datasource.password=1234
# ===============================
# FLYWAY MIGRATION
# ===============================
spring.flyway.enabled=false
spring.flyway.validate-on-migrate=true
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.root=INFO
logging.level.com.alligator.market=INFO
logging.level.reactor.netty.http.client=INFO
logging.file.path=logs
# ===============================
# KAFKA CONFIGURATION
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.schema.registry.url=http://localhost:8082
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
# ==================================
# MARKET DATA PROVIDER CONFIGURATION
# ==================================
provider.maintenance.on-startup=true
provider.maintenance.fail-fast=true
provider.maintenance.tasks.provider-passport-db-projection.enabled=true
# MOEX ISS connection configuration:
provider.connection-properties.moex.iss.fx-spot.base-url=https://iss.moex.com/iss
# ==========================
# QUOTE STREAM CONFIGURATION
# ==========================
quotes.smoke.enabled=false
quotes.streaming.enabled=false

