/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.alligator.core.fx.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PriceTick extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1414614991737514563L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PriceTick\",\"namespace\":\"com.alligator.market.core\",\"fields\":[{\"name\":\"pair\",\"type\":\"string\"},{\"name\":\"bid\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":18,\"scale\":6}},{\"name\":\"ask\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":18,\"scale\":6}},{\"name\":\"ts\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"provider\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<PriceTick> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PriceTick> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PriceTick> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PriceTick> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PriceTick> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PriceTick to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PriceTick from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PriceTick instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PriceTick fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence pair;
  private java.nio.ByteBuffer bid;
  private java.nio.ByteBuffer ask;
  private java.time.Instant ts;
  private java.lang.CharSequence provider;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PriceTick() {}

  /**
   * All-args constructor.
   * @param pair The new value for pair
   * @param bid The new value for bid
   * @param ask The new value for ask
   * @param ts The new value for ts
   * @param provider The new value for provider
   */
  public PriceTick(java.lang.CharSequence pair, java.nio.ByteBuffer bid, java.nio.ByteBuffer ask, java.time.Instant ts, java.lang.CharSequence provider) {
    this.pair = pair;
    this.bid = bid;
    this.ask = ask;
    this.ts = ts.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.provider = provider;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pair;
    case 1: return bid;
    case 2: return ask;
    case 3: return ts;
    case 4: return provider;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pair = (java.lang.CharSequence)value$; break;
    case 1: bid = (java.nio.ByteBuffer)value$; break;
    case 2: ask = (java.nio.ByteBuffer)value$; break;
    case 3: ts = (java.time.Instant)value$; break;
    case 4: provider = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pair' field.
   * @return The value of the 'pair' field.
   */
  public java.lang.CharSequence getPair() {
    return pair;
  }


  /**
   * Sets the value of the 'pair' field.
   * @param value the value to set.
   */
  public void setPair(java.lang.CharSequence value) {
    this.pair = value;
  }

  /**
   * Gets the value of the 'bid' field.
   * @return The value of the 'bid' field.
   */
  public java.nio.ByteBuffer getBid() {
    return bid;
  }


  /**
   * Sets the value of the 'bid' field.
   * @param value the value to set.
   */
  public void setBid(java.nio.ByteBuffer value) {
    this.bid = value;
  }

  /**
   * Gets the value of the 'ask' field.
   * @return The value of the 'ask' field.
   */
  public java.nio.ByteBuffer getAsk() {
    return ask;
  }


  /**
   * Sets the value of the 'ask' field.
   * @param value the value to set.
   */
  public void setAsk(java.nio.ByteBuffer value) {
    this.ask = value;
  }

  /**
   * Gets the value of the 'ts' field.
   * @return The value of the 'ts' field.
   */
  public java.time.Instant getTs() {
    return ts;
  }


  /**
   * Sets the value of the 'ts' field.
   * @param value the value to set.
   */
  public void setTs(java.time.Instant value) {
    this.ts = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'provider' field.
   * @return The value of the 'provider' field.
   */
  public java.lang.CharSequence getProvider() {
    return provider;
  }


  /**
   * Sets the value of the 'provider' field.
   * @param value the value to set.
   */
  public void setProvider(java.lang.CharSequence value) {
    this.provider = value;
  }

  /**
   * Creates a new PriceTick RecordBuilder.
   * @return A new PriceTick RecordBuilder
   */
  public static PriceTick.Builder newBuilder() {
    return new PriceTick.Builder();
  }

  /**
   * Creates a new PriceTick RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PriceTick RecordBuilder
   */
  public static PriceTick.Builder newBuilder(PriceTick.Builder other) {
    if (other == null) {
      return new PriceTick.Builder();
    } else {
      return new PriceTick.Builder(other);
    }
  }

  /**
   * Creates a new PriceTick RecordBuilder by copying an existing PriceTick instance.
   * @param other The existing instance to copy.
   * @return A new PriceTick RecordBuilder
   */
  public static PriceTick.Builder newBuilder(PriceTick other) {
    if (other == null) {
      return new PriceTick.Builder();
    } else {
      return new PriceTick.Builder(other);
    }
  }

  /**
   * RecordBuilder for PriceTick instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PriceTick>
    implements org.apache.avro.data.RecordBuilder<PriceTick> {

    private java.lang.CharSequence pair;
    private java.nio.ByteBuffer bid;
    private java.nio.ByteBuffer ask;
    private java.time.Instant ts;
    private java.lang.CharSequence provider;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(PriceTick.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pair)) {
        this.pair = data().deepCopy(fields()[0].schema(), other.pair);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bid)) {
        this.bid = data().deepCopy(fields()[1].schema(), other.bid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ask)) {
        this.ask = data().deepCopy(fields()[2].schema(), other.ask);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.provider)) {
        this.provider = data().deepCopy(fields()[4].schema(), other.provider);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing PriceTick instance
     * @param other The existing instance to copy.
     */
    private Builder(PriceTick other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.pair)) {
        this.pair = data().deepCopy(fields()[0].schema(), other.pair);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bid)) {
        this.bid = data().deepCopy(fields()[1].schema(), other.bid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ask)) {
        this.ask = data().deepCopy(fields()[2].schema(), other.ask);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts)) {
        this.ts = data().deepCopy(fields()[3].schema(), other.ts);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.provider)) {
        this.provider = data().deepCopy(fields()[4].schema(), other.provider);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'pair' field.
      * @return The value.
      */
    public java.lang.CharSequence getPair() {
      return pair;
    }


    /**
      * Sets the value of the 'pair' field.
      * @param value The value of 'pair'.
      * @return This builder.
      */
    public PriceTick.Builder setPair(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.pair = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pair' field has been set.
      * @return True if the 'pair' field has been set, false otherwise.
      */
    public boolean hasPair() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pair' field.
      * @return This builder.
      */
    public PriceTick.Builder clearPair() {
      pair = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBid() {
      return bid;
    }


    /**
      * Sets the value of the 'bid' field.
      * @param value The value of 'bid'.
      * @return This builder.
      */
    public PriceTick.Builder setBid(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.bid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bid' field has been set.
      * @return True if the 'bid' field has been set, false otherwise.
      */
    public boolean hasBid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bid' field.
      * @return This builder.
      */
    public PriceTick.Builder clearBid() {
      bid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ask' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getAsk() {
      return ask;
    }


    /**
      * Sets the value of the 'ask' field.
      * @param value The value of 'ask'.
      * @return This builder.
      */
    public PriceTick.Builder setAsk(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.ask = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ask' field has been set.
      * @return True if the 'ask' field has been set, false otherwise.
      */
    public boolean hasAsk() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ask' field.
      * @return This builder.
      */
    public PriceTick.Builder clearAsk() {
      ask = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ts' field.
      * @return The value.
      */
    public java.time.Instant getTs() {
      return ts;
    }


    /**
      * Sets the value of the 'ts' field.
      * @param value The value of 'ts'.
      * @return This builder.
      */
    public PriceTick.Builder setTs(java.time.Instant value) {
      validate(fields()[3], value);
      this.ts = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ts' field has been set.
      * @return True if the 'ts' field has been set, false otherwise.
      */
    public boolean hasTs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ts' field.
      * @return This builder.
      */
    public PriceTick.Builder clearTs() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'provider' field.
      * @return The value.
      */
    public java.lang.CharSequence getProvider() {
      return provider;
    }


    /**
      * Sets the value of the 'provider' field.
      * @param value The value of 'provider'.
      * @return This builder.
      */
    public PriceTick.Builder setProvider(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.provider = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'provider' field has been set.
      * @return True if the 'provider' field has been set, false otherwise.
      */
    public boolean hasProvider() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'provider' field.
      * @return This builder.
      */
    public PriceTick.Builder clearProvider() {
      provider = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PriceTick build() {
      try {
        PriceTick record = new PriceTick();
        record.pair = fieldSetFlags()[0] ? this.pair : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.bid = fieldSetFlags()[1] ? this.bid : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        record.ask = fieldSetFlags()[2] ? this.ask : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.ts = fieldSetFlags()[3] ? this.ts : (java.time.Instant) defaultValue(fields()[3]);
        record.provider = fieldSetFlags()[4] ? this.provider : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PriceTick>
    WRITER$ = (org.apache.avro.io.DatumWriter<PriceTick>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PriceTick>
    READER$ = (org.apache.avro.io.DatumReader<PriceTick>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










